/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto.vista;

import com.proyecto.beans.Contrato;
import com.proyecto.beans.Empleado;
import com.proyecto.beans.MotivoBajaTrabajador;
import com.proyecto.beans.PeriodoRegimenPension;
import com.proyecto.beans.PeriodoRegimenSalud;
import com.proyecto.beans.PeriodoTipoTrabajador;
import com.proyecto.beans.RegimenAseguramiento;
import com.proyecto.beans.RegimenPensionario;
import com.proyecto.beans.TipoContrato;
import com.proyecto.beans.TipoPago;
import com.proyecto.beans.TipoTrabajador;
import com.proyecto.control.AbstractControlador;
import com.proyecto.control.ContratoControlador;
import com.proyecto.control.MotivoBajaTrabajadorControlador;
import com.proyecto.control.PeriodoRegimenPensionControlador;
import com.proyecto.control.PeriodoRegimenSaludControlador;
import com.proyecto.control.PeriodoTipoTrabajadorControlador;
import com.proyecto.control.RegimenAseguramientoControlador;
import com.proyecto.control.RegimenPensionarioControlador;
import com.proyecto.control.TipoContratoControlador;
import com.proyecto.control.TipoPagoControlador;
import com.proyecto.control.TipoTrabajadorControlador;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.Converter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Documentos
 */
public class MantenimientoContrato extends javax.swing.JInternalFrame {

    /**
     * Creates new form MantenimientoContrato
     */
    private static MantenimientoContrato instancia;

    public MantenimientoContrato() {
        initComponents();

        listar();
        FormularioUtil.activarComponente(panelDatos, false);
        FormularioUtil.activarComponente(panelOpciones, true);
        FormularioUtil.activarComponente(panelGuardar, false);
    }

    public static MantenimientoContrato getInstancia() {
        if (instancia == null) {
            instancia = new MantenimientoContrato();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        empleadoField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContratos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        chckVigenteContrato = new javax.swing.JCheckBox();
        panelOpciones = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbPeriodicidad = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        chckVida = new javax.swing.JCheckBox();
        chckAsigFam = new javax.swing.JCheckBox();
        chckVigenteC = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDetalle1 = new javax.swing.JButton();
        btnDetalle2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmbRegimenSalud = new javax.swing.JComboBox();
        btnDetalle3 = new javax.swing.JButton();
        cmbRegimenPension = new javax.swing.JComboBox();
        cmbTipoTrabajador = new javax.swing.JComboBox();
        cmbTipoPago = new javax.swing.JComboBox();
        jdateInicial = new com.toedter.calendar.JDateChooser();
        jdateFinal = new com.toedter.calendar.JDateChooser();
        spnSueldo = new javax.swing.JSpinner();
        cmbTipoContrato = new javax.swing.JComboBox();
        cmbMotivoBaja = new javax.swing.JComboBox();
        panelGuardar = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setTitle("ACTUALIZACION DE CONTRATOS LABORALES");
        setFont(new java.awt.Font("Adobe Arabic", 1, 10)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblContratos);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chckVigenteContrato.setText("Vigente");
        chckVigenteContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckVigenteContratoActionPerformed(evt);
            }
        });

        jButton12.setText("Nuevo");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Modificar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(empleadoField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                        .addComponent(chckVigenteContrato))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(chckVigenteContrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Fecha Inicial:");

        jLabel2.setText("Fecha Final:");

        jLabel3.setText("Sueldo Base:");

        jLabel4.setText("Tipo Contrato: ");

        jLabel5.setText("Tipo de Pago:");

        jLabel6.setText("Periodicidad:");

        jLabel7.setText("Motivo de Baja:");

        chckVida.setText("Vida");

        chckAsigFam.setText("Asig. Familiar");

        chckVigenteC.setText("Vigente");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setText("Tipo de Trabajador:");

        jLabel9.setText("Régimen Pensionario: ");

        btnDetalle1.setText("Detalle");
        btnDetalle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalle1ActionPerformed(evt);
            }
        });

        btnDetalle2.setText("Detalle");
        btnDetalle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalle2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Régimen de Salud:");

        btnDetalle3.setText("Detalle");
        btnDetalle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalle3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbRegimenSalud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbRegimenPension, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipoTrabajador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDetalle1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDetalle2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDetalle3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalle1)
                    .addComponent(cmbTipoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalle2)
                    .addComponent(cmbRegimenPension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRegimenSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalle3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spnSueldo.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(chckVida)
                                .addGap(119, 119, 119)
                                .addComponent(chckAsigFam)
                                .addGap(113, 113, 113)
                                .addComponent(chckVigenteC))
                            .addComponent(cmbMotivoBaja, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipoContrato, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(cmbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(cmbPeriodicidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosLayout.createSequentialGroup()
                                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jdateInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jdateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(spnSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdateInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbMotivoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chckVida)
                    .addComponent(chckAsigFam)
                    .addComponent(chckVigenteC))
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalle1ActionPerformed
        // TODO add your handling code here:
        MantenimientoPeriodoTipoTrabajador periodoTrabajador = new MantenimientoPeriodoTipoTrabajador();
        Principal.desktoppane.add(periodoTrabajador);
        periodoTrabajador.toFront();
        periodoTrabajador.setVisible(true);


    }//GEN-LAST:event_btnDetalle1ActionPerformed

    private void btnDetalle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalle2ActionPerformed
        // TODO add your handling code here:

        MantenimientoPeriodoRegimenPension regimenPension = new MantenimientoPeriodoRegimenPension();
        Principal.desktoppane.add(regimenPension);
        regimenPension.toFront();
        regimenPension.setVisible(true);
    }//GEN-LAST:event_btnDetalle2ActionPerformed

    private void btnDetalle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalle3ActionPerformed
        // TODO add your handling code here:
        MantenimientoPeriodoRegimenSalud regimenSalud = new MantenimientoPeriodoRegimenSalud();
        Principal.desktoppane.add(regimenSalud);
        regimenSalud.toFront();
        regimenSalud.setVisible(true);

    }//GEN-LAST:event_btnDetalle3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DlgEmpleadoBusqueda empleadoDialogo = new DlgEmpleadoBusqueda(this);

        if (contratoControlador.getSeleccionado() == null) {
            Contrato contratoProv = new Contrato();
            contratoControlador.setSeleccionado(contratoProv);
        }
        contratoControlador.getSeleccionado().setEmpleado(empleadoDialogo.getEmpleado());
        this.empleadoField.setText(contratoControlador.getSeleccionado().getEmpleado().getNombre().toUpperCase() + ", "
                + contratoControlador.getSeleccionado().getEmpleado().getApellidoPaterno().toUpperCase() + " "
                + contratoControlador.getSeleccionado().getEmpleado().getApellidoMaterno().toUpperCase());
        lista.clear();
        lista.addAll(this.contratoControlador.buscarXEmpleado(this.contratoControlador.getSeleccionado().getEmpleado()));
        empleadin = this.contratoControlador.getSeleccionado().getEmpleado();
    }//GEN-LAST:event_jButton1ActionPerformed
    Empleado empleadin = new Empleado();

    private void chckVigenteContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckVigenteContratoActionPerformed
        // TODO add your handling code here:
        if (chckVigenteContrato.isSelected()) {
            lista.clear();
            lista.addAll(this.contratoControlador.buscarXContratoVigente(empleadin, true));
        } else {
            lista.clear();
            lista.addAll(this.contratoControlador.buscarXContratoVigente(empleadin, false));

        }
    }//GEN-LAST:event_chckVigenteContratoActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        accion = AbstractControlador.NUEVO;
        contratoControlador.prepararCrear();

        FormularioUtil.activarComponente(panelOpciones, false);
        FormularioUtil.activarComponente(panelGuardar, true);
        FormularioUtil.activarComponente(panelDatos, true);
        jdateInicial.requestFocusInWindow();
        FormularioUtil.limpiarComponente(panelDatos);
        empleadoField.setText(null);
        cargarCombos();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        accion = AbstractControlador.MODIFICAR;
        int fila = this.tblContratos.getSelectedRow();
        if (fila != -1) {
            FormularioUtil.activarComponente(panelDatos, true);
            FormularioUtil.activarComponente(panelOpciones, false);
            FormularioUtil.activarComponente(panelGuardar, true);

            accion = AbstractControlador.MODIFICAR;
            contratoControlador.setSeleccionado(lista.get(fila));
            Contrato contrato = contratoControlador.getSeleccionado();

            jdateInicial.setDate(contrato.getFechaInicio());
            jdateFinal.setDate(contrato.getFechaFin());
            spnSueldo.setValue(contrato.getSueldoBase());
            chckVida.setSelected(contrato.isVida());
            chckAsigFam.setSelected(contrato.isAsignacionFam());
            chckVigenteC.setSelected(contrato.getVigente());

            cmbTipoPago.setSelectedItem(contrato.getTipoPago());
            cmbTipoContrato.setSelectedItem(contrato.getTipoContrato());
            cmbMotivoBaja.setSelectedItem(contrato.getMotivoBajaTrabajador());
//            cmbTipoTrabajador.setSelectedItem(contrato.getPeriodoTipoTrabajador().getTipoTrabajador().getDescripcion());
//            cmbRegimenPension.setSelectedItem(contrato.getPeriodoRegimenPension().getRegimenPensionario());
//            cmbRegimenSalud.setSelectedItem(contrato.getPeriodoRegimenSalud().getRegimenAseguramiento());
            cmbPeriodicidad.setSelectedItem(contrato.getPeriodicidad());

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Contrato", "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String palabra = "";
        String palabra2 = "";
        if (accion == 1) {
            palabra = "registrar";
            palabra2 = "registrado";

            if (JOptionPane.showConfirmDialog(null, "¿Desea " + palabra + " el Contrato?", "Mensaje del Sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                contratoControlador.getSeleccionado().setFechaInicio(jdateInicial.getDate());
                contratoControlador.getSeleccionado().setFechaFin(jdateFinal.getDate());
                contratoControlador.getSeleccionado().setSueldoBase((Double) spnSueldo.getModel().getValue());
                contratoControlador.getSeleccionado().setVida(chckVida.isSelected());
                contratoControlador.getSeleccionado().setAsignacionFam(chckAsigFam.isSelected());
                contratoControlador.getSeleccionado().setVigente(chckVigenteC.isSelected());

                contratoControlador.getSeleccionado().setTipoContrato((TipoContrato) cmbTipoContrato.getSelectedItem());
                contratoControlador.getSeleccionado().setTipoPago((TipoPago) cmbTipoPago.getSelectedItem());
                contratoControlador.getSeleccionado().setPeriodicidad(cmbPeriodicidad.getSelectedItem().toString());
                contratoControlador.getSeleccionado().setMotivoBajaTrabajador((MotivoBajaTrabajador) cmbMotivoBaja.getSelectedItem());

                //PERIODO DEL TIPO DE TRABAJADOR
                PeriodoTipoTrabajador periodoTrabajador = new PeriodoTipoTrabajador();

                PeriodoTipoTrabajadorControlador pt = new PeriodoTipoTrabajadorControlador();
                pt.setSeleccionado(periodoTrabajador);
//                pt.prepararCrear();

                pt.getSeleccionado().setFechaInicio(jdateInicial.getDate());
                pt.getSeleccionado().setFechaFin(jdateFinal.getDate());
                pt.getSeleccionado().setNombre(((TipoTrabajador) cmbTipoTrabajador.getSelectedItem()).getDescripcion());
                pt.getSeleccionado().setTipoTrabajador(((TipoTrabajador) cmbTipoTrabajador.getSelectedItem()));
                pt.getSeleccionado().setVigente(true);

//                contratoControlador.getSeleccionado().setPeriodoTipoTrabajador(periodoTrabajador);
                //PERIODO DEL REGIMEN DE PENSION
                System.out.println("fecha fin: " + jdateFinal.getDate());
                PeriodoRegimenPension regimenPension = new PeriodoRegimenPension();

                PeriodoRegimenPensionControlador rp = new PeriodoRegimenPensionControlador();
                rp.setSeleccionado(regimenPension);
//                rp.prepararCrear();

                rp.getSeleccionado().setFechaInicio(jdateInicial.getDate());
                rp.getSeleccionado().setFechaFin(jdateFinal.getDate());
                System.out.println("FECHA FIN ::: " + rp.getSeleccionado().getFechaFin());
                rp.getSeleccionado().setNombre(((RegimenPensionario) cmbRegimenPension.getSelectedItem()).getDescripcion());
                rp.getSeleccionado().setRegimenPensionario((RegimenPensionario) cmbRegimenPension.getSelectedItem());
                rp.getSeleccionado().setVigente(true);

//                contratoControlador.getSeleccionado().setPeriodoRegimenPension(regimenPension);
                //PERIODO DEL REGIMEN DE SALUD
                PeriodoRegimenSalud regimenSalud = new PeriodoRegimenSalud();

                PeriodoRegimenSaludControlador rs = new PeriodoRegimenSaludControlador();
                rs.setSeleccionado(regimenSalud);
//                rs.prepararCrear();

                rs.getSeleccionado().setFechaInicio(jdateInicial.getDate());
                rs.getSeleccionado().setFechaFin(jdateFinal.getDate());
                rs.getSeleccionado().setNombre(((RegimenAseguramiento) cmbRegimenSalud.getSelectedItem()).getNombre());
                rs.getSeleccionado().setRegimenAseguramiento((RegimenAseguramiento) cmbRegimenSalud.getSelectedItem());
                rs.getSeleccionado().setVigente(true);

//                contratoControlador.getSeleccionado().setPeriodoRegimenSalud(regimenSalud);
                contratoControlador.accion(accion);

                //CONTRATO - > PERIODO REGIMEN SALUD
                rs.accion(accion);

                //CONTRATO -> PERIODO REGIMEN PENSION
                rp.accion(accion);

                //CONTRATO -> PERIODO TIPO TRABAJADOR
                pt.accion(accion);

                lista.add(contratoControlador.getSeleccionado());

                if (accion == 1) {
                    JOptionPane.showMessageDialog(null, "Contrato " + palabra2 + " correctamente", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
                    FormularioUtil.limpiarComponente(panelDatos);
                    cargarCombos();
                } else {
                    JOptionPane.showMessageDialog(null, "Contrato no " + palabra2, "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                FormularioUtil.limpiarComponente(panelDatos);
                cargarCombos();
                JOptionPane.showMessageDialog(null, "Contrato no " + palabra2, "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
            }
        } else if (accion == 2) {
            palabra = "modificar";
            palabra2 = "modificado";

            if (JOptionPane.showConfirmDialog(null, "¿Desea " + palabra + " el Contrato?", "Mensaje del Sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                if (accion == 2) {
                    JOptionPane.showMessageDialog(null, "Contrato " + palabra2 + " correctamente", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);

                    lista.clear();
                    contratoControlador.getSeleccionado().setFechaInicio(jdateInicial.getDate());
                    contratoControlador.getSeleccionado().setFechaFin(jdateFinal.getDate());
                    contratoControlador.getSeleccionado().setSueldoBase((Double) spnSueldo.getModel().getValue());
                    contratoControlador.getSeleccionado().setVida(chckVida.isSelected());
                    contratoControlador.getSeleccionado().setAsignacionFam(chckAsigFam.isSelected());
                    contratoControlador.getSeleccionado().setVigente(chckVigenteC.isSelected());

                    contratoControlador.getSeleccionado().setTipoContrato((TipoContrato) cmbTipoContrato.getSelectedItem());
                    contratoControlador.getSeleccionado().setTipoPago((TipoPago) cmbTipoPago.getSelectedItem());
                    contratoControlador.getSeleccionado().setPeriodicidad(cmbPeriodicidad.getSelectedItem().toString());
                    contratoControlador.getSeleccionado().setMotivoBajaTrabajador((MotivoBajaTrabajador) cmbMotivoBaja.getSelectedItem());

//                    contratoControlador.getSeleccionado().getPeriodoTipoTrabajador().setFechaInicio(jdateInicial.getDate());
//                    contratoControlador.getSeleccionado().getPeriodoTipoTrabajador().setFechaFin(jdateFinal.getDate());
//                    
//                    contratoControlador.getSeleccionado().getPeriodoRegimenPension().setFechaInicio(jdateInicial.getDate());
//                    contratoControlador.getSeleccionado().getPeriodoRegimenPension().setFechaFin(jdateFinal.getDate());
//                    
//                    contratoControlador.getSeleccionado().getPeriodoRegimenSalud().setFechaInicio(jdateInicial.getDate());
//                    contratoControlador.getSeleccionado().getPeriodoRegimenSalud().setFechaFin(jdateFinal.getDate());
                    contratoControlador.accion(accion);
                    listar();

                    FormularioUtil.limpiarComponente(panelDatos);
                    cargarCombos();

                } else {
                    JOptionPane.showMessageDialog(null, "Contrato no " + palabra2, "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                FormularioUtil.limpiarComponente(panelDatos);
                cargarCombos();
                JOptionPane.showMessageDialog(null, "Contrato no " + palabra2, "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
            }
        }

        FormularioUtil.activarComponente(panelOpciones, true);
        FormularioUtil.activarComponente(panelGuardar, false);
        FormularioUtil.activarComponente(panelDatos, false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FormularioUtil.activarComponente(panelDatos, false);
        FormularioUtil.limpiarComponente(panelDatos);
        FormularioUtil.activarComponente(panelOpciones, true);
        FormularioUtil.activarComponente(panelGuardar, false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private final ContratoControlador contratoControlador = new ContratoControlador();
    private List<Contrato> lista;
    private int accion;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalle1;
    private javax.swing.JButton btnDetalle2;
    private javax.swing.JButton btnDetalle3;
    private javax.swing.JCheckBox chckAsigFam;
    private javax.swing.JCheckBox chckVida;
    private javax.swing.JCheckBox chckVigenteC;
    private javax.swing.JCheckBox chckVigenteContrato;
    private javax.swing.JComboBox cmbMotivoBaja;
    private javax.swing.JComboBox cmbPeriodicidad;
    private javax.swing.JComboBox cmbRegimenPension;
    private javax.swing.JComboBox cmbRegimenSalud;
    private javax.swing.JComboBox cmbTipoContrato;
    private javax.swing.JComboBox cmbTipoPago;
    private javax.swing.JComboBox cmbTipoTrabajador;
    private javax.swing.JTextField empleadoField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdateFinal;
    private com.toedter.calendar.JDateChooser jdateInicial;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelGuardar;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JSpinner spnSueldo;
    private javax.swing.JTable tblContratos;
    // End of variables declaration//GEN-END:variables

    private void listar() {
        lista = this.contratoControlador.buscarTodos();
        lista = ObservableCollections.observableList(lista);

        JTableBinding binding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, lista, tblContratos);

        BeanProperty bId = BeanProperty.create("id");
        BeanProperty bFechaInicio = BeanProperty.create("fechaInicio");
        BeanProperty bFechaFin = BeanProperty.create("fechaFin");
        BeanProperty bSueldoBase = BeanProperty.create("sueldoBase");
        BeanProperty bPeriodicidad = BeanProperty.create("periodicidad");

        binding.addColumnBinding(bId).setColumnName("ID").setEditable(false);
        binding.addColumnBinding(bFechaInicio).setColumnName("FECHA_INICIO").setEditable(false);
        binding.addColumnBinding(bFechaFin).setColumnName("FECHA_FIN").setEditable(false);
        binding.addColumnBinding(bSueldoBase).setColumnName("SUELDO_BASE").setEditable(false);
        binding.addColumnBinding(bPeriodicidad).setColumnName("PERIODICIDAD").setEditable(false);

        binding.bind();
    }

    private void cargarComboTipoPago() {
        TipoPagoControlador pago = new TipoPagoControlador();
        List<TipoPago> tipoPago = pago.buscarTodos();
        cmbTipoPago.setModel(new DefaultComboBoxModel(tipoPago.toArray()));
        AutoCompleteDecorator.decorate(this.cmbTipoPago);
    }

    private void cargarComboPeriodicidad() {
        List<String> periodicidad = new ArrayList<>();
        periodicidad.add("POCO");
        periodicidad.add("REGULAR");
        periodicidad.add("MUCHO");
        cmbPeriodicidad.setModel(new DefaultComboBoxModel(periodicidad.toArray()));
        AutoCompleteDecorator.decorate(this.cmbPeriodicidad);
    }

    private void cargarComboTipoTrabajador() {
        TipoTrabajadorControlador trabajador = new TipoTrabajadorControlador();
        List<TipoTrabajador> tipoTrabajador = trabajador.buscarTodos();
        cmbTipoTrabajador.setModel(new DefaultComboBoxModel(tipoTrabajador.toArray()));
        AutoCompleteDecorator.decorate(this.cmbTipoTrabajador);
    }

    private void cargarComboRegimenPension() {
        RegimenPensionarioControlador ac = new RegimenPensionarioControlador();
        List<RegimenPensionario> regimenPension = ac.buscarTodos();
        cmbRegimenPension.setModel(new DefaultComboBoxModel(regimenPension.toArray()));
        AutoCompleteDecorator.decorate(this.cmbRegimenPension);
    }

    private void cargarComboRegimenSalud() {
        RegimenAseguramientoControlador ac = new RegimenAseguramientoControlador();
        List<RegimenAseguramiento> regimenSalud = ac.buscarTodos();
        cmbRegimenSalud.setModel(new DefaultComboBoxModel(regimenSalud.toArray()));
        AutoCompleteDecorator.decorate(this.cmbRegimenSalud);
    }

    private void cargarComboTipoContrato() {
        TipoContratoControlador ac = new TipoContratoControlador();
        List<TipoContrato> tipoContrato = ac.buscarTodos();
        cmbTipoContrato.setModel(new DefaultComboBoxModel(tipoContrato.toArray()));
        AutoCompleteDecorator.decorate(this.cmbTipoContrato);
    }

    private void cargarComboMotivoBaja() {
        MotivoBajaTrabajadorControlador ac = new MotivoBajaTrabajadorControlador();
        List<MotivoBajaTrabajador> motivoBaja = ac.buscarTodos();
        cmbMotivoBaja.setModel(new DefaultComboBoxModel(motivoBaja.toArray()));
        AutoCompleteDecorator.decorate(this.cmbMotivoBaja);
    }

    private void cargarCombos() {
        cargarComboTipoPago();
        cargarComboPeriodicidad();
        cargarComboTipoTrabajador();
        cargarComboRegimenPension();
        cargarComboRegimenSalud();
        cargarComboMotivoBaja();
        cargarComboTipoContrato();
    }
}
