/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto.vista;

import com.proyecto.beans.Contrato;
import com.proyecto.beans.PorcentajeAFP;
import com.proyecto.beans.RegimenPensionario;
import com.proyecto.control.AbstractControlador;
import com.proyecto.control.ContratoControlador;
import com.proyecto.control.PorcentajeAFPControlador;
import com.proyecto.control.RegimenPensionarioControlador;
import com.proyecto.util.TableColumnAdjuster;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JTable;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Documentos
 */
public class MantenimientoPorcentajeAFP extends javax.swing.JInternalFrame {

    /**
     * Creates new form MantenimientoPorcentajeAFP
     */
    private static MantenimientoPorcentajeAFP instancia;

    public MantenimientoPorcentajeAFP() {
        initComponents();
        
//        lista.add(new PorcentajeAFP());
//        lista.add(new PorcentajeAFP());
//        lista.add(new PorcentajeAFP());
//        lista.add(new PorcentajeAFP());
        
//        tblPorcentajes.setModel(new MiTabla(lista));
//        prueba();
//        
        listar();
        
    }

    public static MantenimientoPorcentajeAFP getInstancia() {
        if (instancia == null) {
            instancia = new MantenimientoPorcentajeAFP();
        }
        return instancia;
    }

    private void prueba() {
        RegimenPensionarioControlador test = new RegimenPensionarioControlador();
        List<RegimenPensionario> listilla = test.buscarXFiltro();

        for (RegimenPensionario listilla1 : listilla) {
//            listaPrueba.add();
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPorcentajes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMes = new com.toedter.calendar.JMonthChooser();
        jAnio = new com.toedter.calendar.JYearChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Mantenimiento Porcentajes AFP");

        tblPorcentajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPorcentajes);

        jLabel1.setText("Periodo:");

        jButton1.setText("Nuevo");

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jMes, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private final PorcentajeAFPControlador afpControlador = new PorcentajeAFPControlador();
    private List<PorcentajeAFP> lista = new ArrayList();
    private List<PorcentajeAFP> listaPrueba;
    private int accion;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser jAnio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JMonthChooser jMes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPorcentajes;
    // End of variables declaration//GEN-END:variables

    List<RegimenPensionario> lista2;
    RegimenPensionarioControlador regimenPensionarioControlador = new RegimenPensionarioControlador();
    private void listar() {
        lista = new ArrayList<>();
        lista2 = regimenPensionarioControlador.buscarXFiltro();
//        lista = ObservableCollections.observableList(lista);
        
        for(RegimenPensionario regimen : lista2){
            PorcentajeAFP afp = new PorcentajeAFP();
            afp.setRegimenPensionario(regimen);
            afp.setFondoPension(null);
            afp.setSeguroInvalidez(null);
            afp.setComisionRemFlujo(null);
            afp.setComisionRemMixta(null);
            afp.setTopePrima(null);
            lista.add(afp);
        }
        
        BeanProperty fondoPension = BeanProperty.create("fondoPension");
        BeanProperty seguroInvalidez = BeanProperty.create("seguroInvalidez");
        BeanProperty comisionRemFlujo = BeanProperty.create("comisionRemFlujo");
        BeanProperty comisionRemMixta = BeanProperty.create("comisionRemMixta");
        BeanProperty topePrima = BeanProperty.create("topePrima");
        BeanProperty regimen = BeanProperty.create(BeanProperty.create("regimenPensionario"),"abreviatura");
        
        
        
        JTableBinding binding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, lista, tblPorcentajes);
        
        binding.addColumnBinding(regimen).setColumnName("AFP").setColumnClass(String.class).setEditable(false);
        binding.addColumnBinding(fondoPension).setColumnName("Fondo Pension").setColumnClass(Double.class).setEditable(true);
        binding.addColumnBinding(seguroInvalidez).setColumnName("Seguro Invalidez").setColumnClass(Double.class).setEditable(true);
        binding.addColumnBinding(comisionRemFlujo).setColumnName("Comisión Flujo").setColumnClass(Double.class).setEditable(true);
        binding.addColumnBinding(comisionRemMixta).setColumnName("Comisión Mixta").setColumnClass(Double.class).setEditable(true);
        binding.addColumnBinding(topePrima).setColumnName("Tope prima").setColumnClass(Double.class).setEditable(true);
        
        binding.bind();
        
        ajustarColumnas(tblPorcentajes);
        
        
    }

    private void ajustarColumnas(JTable tabla) {
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnAdjuster tca = new TableColumnAdjuster(tabla);
        tca.adjustColumns();
        
    }
    
    private void guardar(){
        int mes = jMes.getMonth();
        int anio = jAnio.getYear();
        Calendar cal = Calendar.getInstance();
        cal.set(anio, mes, 1);
        for (PorcentajeAFP afp : lista) {
            afp.setPeriodo(cal.getTime());
            afpControlador.setSeleccionado(afp);
            afpControlador.accion(AbstractControlador.MODIFICAR);
        }
    }
}
